server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service-docs
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        - id: wallet-service-docs
          uri: http://localhost:8082
          predicates:
            - Path=/wallet-service/**
          filters:
            - RewritePath=/wallet-service/(?<segment>.*), /${segment}

        - id: user-service-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**,/api/profile/**,/api/business/**,/api/health/**

        - id: wallet-service-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/wallet/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: wallet-service
        url: /wallet-service/v3/api-docs